name: mriqc_docs
channels:
  - conda-forge
dependencies:
- python=3.5
- numpy
- scipy=0.18.1
- scikit-learn=0.18.1
- pandas=0.19.1
- matplotlib=2.0.0
- traits=4.6
- jinja2=2.8
- sphinx>=1.5.1
- sphinx_rtd_theme
- mock
- future
- matplotlib
- nibabel
- seaborn
- PyYAML
- nose
- statsmodels

- pip:
    - doctest-ignore-unicode
    - svgutils
    - nipy
    - dipy
    - nitime
    - nilearn
    - git+https://github.com/poldracklab/niworkflows.git@master
    - git+https://github.com/nipy/nipype.git@master

