name: mriqc_docs
channels:
  - defaults
  - conda-forge
dependencies:
- numpy
- scipy=0.18.1
- scikit-learn=0.18.1
- pandas=0.19.1
- matplotlib=2.0.0
- traits=4.6
- jinja2=2.8
- sphinx>=1.5.1
- sphinx_rtd_theme
- mock
- future
- matplotlib
- nibabel
- seaborn
- PyYAML
- nose
- statsmodels

- pip:
    - doctest-ignore-unicode
    - svgutils
    - nipy
    - dipy
    - nitime
    - nilearn

