name: mriqc
channels:
  - default
  - conda-forge
dependencies:
  - python=3.5
  - numpy=1.12.0
  - scipy=0.18.1
  - scikit-learn=0.18.1
  - pandas=0.19.1
  - matplotlib=2.0.0
  - traits=4.6
  - jinja2=2.8
  - nipy

